[project]
name = "financial-research-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ddgs>=9.14.4",
    "google-api>=0.1.12",
    "google-auth>=2.56.3",
    "langchain>=1.3.14",
    "langchain-community>=0.4.2",
    "langchain-google-community>=5.0.0",
    "langchain-groq>=1.1.3",
    "python-dotenv>=1.2.2",
    "streamlit>=1.61.1",
    "transformers>=5.14.1",
    "wikipedia>=1.4.0",
]

[project.scripts]
financial-research-assistant = "financial_research_assistant:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.pyright]
extraPaths = ["."]

