from pydantic import BaseModel
from services.llm import get_llm
from models.schemas import InvestmentReport


def generate_investment_report(
    company: str,
    research_text: str,
    news_text: str,
    pdf_context: str = "",
    investor_profile_summary: str = "",
) -> InvestmentReport:
    """
    Generate a structured investment report using Pydantic structured output.
    """
    prompt = f"""
You are a Senior Investment Research Analyst.

Generate a complete, professional investment research report for: {company}

INVESTOR PROFILE:
{investor_profile_summary or "Not provided."}

COMPANY RESEARCH:
{research_text}

LATEST NEWS:
{news_text}

PDF / ANNUAL REPORT CONTEXT:
{pdf_context or "No PDF provided."}

Your report must include:
- company: Company name
- company_overview: Detailed overview of what the company does
- industry: Overview of the industry and sector
- business_model: Revenue sources, value proposition, how they make money
- latest_news: List of 3-5 key recent news items as bullet points
- strengths: List of 4-6 key competitive strengths
- weaknesses: List of 3-5 significant weaknesses or risks
- financial_highlights: Revenue, profit margins, growth rates, EPS, and key ratios
- growth_opportunities: List of 3-5 potential catalysts and growth drivers
- potential_risks: List of 3-5 key risks
- investment_summary: A clear Buy/Hold/Sell recommendation with concise rationale

Base all analysis strictly on the provided research data. Be objective, precise, and professional.
"""

    llm = get_llm()
    structured_llm = llm.with_structured_output(InvestmentReport)
    report = structured_llm.invoke(prompt)
    if isinstance(report, InvestmentReport):
        return report
    if isinstance(report, dict):
        return InvestmentReport.model_validate(report)
    if isinstance(report, BaseModel):
        return InvestmentReport.model_validate(report.model_dump())
    raise ValueError(f"Failed to generate valid InvestmentReport: {report}")


def format_report_as_markdown(report: InvestmentReport) -> str:
    """
    Format an InvestmentReport Pydantic object as a clean markdown document.
    """
    lines = [
        f"# Investment Research Report: {report.company}",
        "",
        "---",
        "",
        "## 🏢 Company Overview",
        report.company_overview,
        "",
        "## 🏭 Industry",
        report.industry,
        "",
        "## 💼 Business Model",
        report.business_model,
        "",
        "## 📰 Latest News",
    ]
    for item in (report.latest_news or []):
        lines.append(f"- {item}")

    lines += [
        "",
        "## 💪 Strengths",
    ]
    for item in (report.strengths or []):
        lines.append(f"- {item}")

    lines += [
        "",
        "## ⚠️ Weaknesses",
    ]
    for item in (report.weaknesses or []):
        lines.append(f"- {item}")

    lines += [
        "",
        "## 📊 Financial Highlights",
        report.financial_highlights,
        "",
        "## 🚀 Growth Opportunities",
    ]
    for item in (report.growth_opportunities or []):
        lines.append(f"- {item}")

    lines += [
        "",
        "## ⚡ Potential Risks",
    ]
    for item in (report.potential_risks or []):
        lines.append(f"- {item}")

    lines += [
        "",
        "---",
        "",
        "## 🎯 Investment Summary",
        report.investment_summary,
        "",
        "---",
        "*Report generated by AI Financial Research Assistant*",
    ]

    return "\n".join(lines)
